<?php

namespace AppBundle\Repository;

/**
 * EscuelasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscuelasRepository extends \Doctrine\ORM\EntityRepository
{
}
