eventos:
    resource: '@EventosBundle/Resources/config/routing.yml'

invitados:
    resource: '@InvitadosBundle/Resources/config/routing.yml'

lugares:
    resource: '@LugaresBundle/Resources/config/routing.yml'

app:
    resource: '@AppBundle/Resources/config/routing.yml'