<?php

namespace InvitadosBundle\Repository;

/**
 * InvitadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitadosRepository extends \Doctrine\ORM\EntityRepository
{
}
