<?php

namespace LugaresBundle\Repository;

/**
 * LugaresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LugaresRepository extends \Doctrine\ORM\EntityRepository
{
}
